// Generated by https://quicktype.io

export interface Story {
    name:      string;
    multiples: Multiple[];
}

export interface Multiple {
    bg?:          number;
    character?:   number;
    text:         string;
    args?:        Arg[];
    route?:       number;
    backable?:    boolean;
    mood?:        string;
    placeholder?: string;
}

export interface Arg {
    emoji?: string;
    label:  string;
    route:  number;
}
